- .github/workflows/Sonarqube.yml
- .github/workflows/fail.yml
얘는 커밋될 때마다 실행이 된다길래 dev로 넣습니다0
> Fail Workflow 삭제 / Sonarqube 정적분석 Workflow 추가

- src/main/java/com/dokebi/dalkom/domain/cart/controller/OrderCartController.java
- src/main/java/com/dokebi/dalkom/domain/cart/dto/OrderCartReadResponse.java
- src/main/java/com/dokebi/dalkom/domain/cart/repository/OrderCartRepository.java
- src/main/java/com/dokebi/dalkom/domain/cart/service/OrderCartService.java
- src/main/java/com/dokebi/dalkom/domain/order/entity/OrderDetail.java
특정 유저의 장바구니에 상품 담기
특정 유저의 장바구니에 상품 담기
> [DOK-149] 특정 유저의 장바구니에 상품 담기

- .github/workflows/PRDecoration.yml
- build.gradle
SonarQube gradle 추가
SonarQube PR Decoration Workflow 추가
SonarQube gradle 추가
SonarQube PR Decoration Workflow 추가
> PR Decoration용 Workflow 추가

- src/main/java/com/dokebi/dalkom/domain/order/repository/OrderDetailRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/controller/ReviewController.java
- src/main/java/com/dokebi/dalkom/domain/review/dto/ReviewCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/review/dto/ReviewModifyRequest.java
- src/main/java/com/dokebi/dalkom/domain/review/entity/Review.java
- src/main/java/com/dokebi/dalkom/domain/review/repository/ReviewRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/service/ReviewService.java
> [Dok 89] 리뷰 CUD

- src/main/java/com/dokebi/dalkom/domain/product/dto/ReadProductResponse.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
리스트에 재고 및 옵션 추가
리포지토리 및 DTO 수정
> [DOK-107] 리스트에 재고 및 옵션 추가

- src/main/java/com/dokebi/dalkom/domain/cart/dto/OrderCartCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/cart/dto/OrderCartReadResponse.java
- src/main/java/com/dokebi/dalkom/domain/cart/entity/OrderCart.java
- src/main/java/com/dokebi/dalkom/domain/cart/repository/OrderCartRepository.java
- src/main/java/com/dokebi/dalkom/domain/cart/service/OrderCartService.java
특정 유저의 장바구니 목록 조회 코드 수정
특정 유저의 장바구니 목록 조회 코드 수정
> [DOK-149] 특정 유저의 장바구니 목록 조회 코드 수정

- src/main/java/com/dokebi/dalkom/domain/mileage/controller/MileageController.java
- src/main/java/com/dokebi/dalkom/domain/mileage/dto/MileageHistoryDto.java
- src/main/java/com/dokebi/dalkom/domain/mileage/repository/MileageApplyRepository.java
- src/main/java/com/dokebi/dalkom/domain/mileage/repository/MileageHistoryRepository.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageService.java
> [DOK-102] 마일리지 조회 기능 수정 

- src/main/java/com/dokebi/dalkom/domain/inqury/controller/InquiryController.java
- src/main/java/com/dokebi/dalkom/domain/inqury/dto/InquiryListResponse.java
- src/main/java/com/dokebi/dalkom/domain/inqury/dto/InquiryOneResponse.java
- src/main/java/com/dokebi/dalkom/domain/inqury/repository/InquiryRepository.java
- src/main/java/com/dokebi/dalkom/domain/inqury/service/InquiryService.java
- src/main/java/com/dokebi/dalkom/domain/review/controller/ReviewController.java
- src/main/java/com/dokebi/dalkom/domain/review/dto/ReviewByUserResponse.java
- src/main/java/com/dokebi/dalkom/domain/review/repository/ReviewRepository.java
문의 조회 기능 추가, 리뷰 코드 수정
문의 조회(사용자별, 카테고리별, 상세), 리뷰 코드 수정
> [Dok 86] 문의 조회 / 리뷰 코드 수정

- src/main/java/com/dokebi/dalkom/domain/product/controller/ProductController.java
- src/main/java/com/dokebi/dalkom/domain/stock/exception/InvalidAmountException.java
- src/main/java/com/dokebi/dalkom/domain/stock/exception/NotEnoughStockException.java
- src/main/java/com/dokebi/dalkom/domain/stock/repository/ProductStockRepository.java
- src/main/java/com/dokebi/dalkom/domain/stock/service/ProductStockService.java
주문 기능에 사용할 메서드 추가 / 재고 음수로 내려가지 않도록 예외 추가
서비스에 orderStock, checkStock 메서드 추가, 리포지토리에 대응하는 메서드 추가, InvalidAmountException, NotEnoughStockException 추가
> [DOK-109] 주문 기능에 사용할 메서드 추가 / 재고 음수로 내려가지 않도록 예외 추가

- src/main/java/com/dokebi/dalkom/domain/mileage/controller/MileageAskController.java
- src/main/java/com/dokebi/dalkom/domain/mileage/controller/MileageController.java
- src/main/java/com/dokebi/dalkom/domain/mileage/dto/MileageAskRequest.java
- src/main/java/com/dokebi/dalkom/domain/mileage/dto/MileageAskResponse.java
- src/main/java/com/dokebi/dalkom/domain/mileage/entity/MileageHistory.java
- src/main/java/com/dokebi/dalkom/domain/mileage/repository/MileageAskRepository.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageAskService.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageService.java
> [DOK-85] 마일리지 신청 처리 후 마일리지 히스토리 변경 

- src/main/java/com/dokebi/dalkom/domain/admin/repository/AdminRepository.java
- src/main/java/com/dokebi/dalkom/domain/inqury/controller/InquiryController.java
- src/main/java/com/dokebi/dalkom/domain/notice/controller/NoticeController.java
- src/main/java/com/dokebi/dalkom/domain/notice/dto/NoticeCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/notice/dto/NoticeListResponse.java
- src/main/java/com/dokebi/dalkom/domain/notice/dto/NoticeModifyRequest.java
- src/main/java/com/dokebi/dalkom/domain/notice/dto/NoticeOneResponse.java
- src/main/java/com/dokebi/dalkom/domain/notice/entity/Notice.java
- src/main/java/com/dokebi/dalkom/domain/notice/repository/NoticeRepository.java
- src/main/java/com/dokebi/dalkom/domain/notice/service/NoticeService.java
- src/main/java/com/dokebi/dalkom/domain/review/controller/ReviewController.java
> [DOK 121] 공지 CRUD

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/cart/exception/OrderCartEmptyResultDataAccessException.java
- src/main/java/com/dokebi/dalkom/domain/cart/service/OrderCartService.java
- src/main/java/com/dokebi/dalkom/domain/inqury/service/InquiryService.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageAskService.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/main/java/com/dokebi/dalkom/domain/product/exception/ProductNotFoundException.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/service/ReviewService.java
- src/main/java/com/dokebi/dalkom/domain/user/repository/UserRepository.java
> [DOK-170] 장바구니 에러 코드

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/order/exception/OrderStockLackException.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
> [DOK-174] 주문 에러 코드 기능 추가

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/stock/service/ProductStockService.java
orderStockLackException, productNotFoundException 추가
> [DOK-171] 재고 관련 exception 2개 추가

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
ExceptionAdvice에서 대문자 카맬로 했던 거 수정
> [DOK-171] 메서드명 스몰카멜로 수정

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/product/exception/InvalidProductInputException.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
InvalidProductInputException 생성
> [DOK-172] 상품에러

- src/main/java/com/dokebi/dalkom/domain/cart/controller/OrderCartController.java
- src/main/java/com/dokebi/dalkom/domain/cart/repository/OrderCartRepository.java
- src/main/java/com/dokebi/dalkom/domain/cart/service/OrderCartService.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/main/java/com/dokebi/dalkom/domain/user/service/UserService.java
[DOK-170] 장바구니 에러 코드 및 메소드명 변경
[DOK-170] 장바구니 에러 코드 및 메소드명 변경
[DOK-170]: https://kea-allways-team.atlassian.net/browse/DOK-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOK-170]: https://kea-allways-team.atlassian.net/browse/DOK-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOK-170] 장바구니 에러 코드 및 메소드명 변경

- src/main/java/com/dokebi/dalkom/domain/order/repository/OrderRepository.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
> [DOK-174] 주문 에러 코드 수정 

- src/main/java/com/dokebi/dalkom/domain/option/entity/ProductOption.java
- src/main/java/com/dokebi/dalkom/domain/stock/entity/ProductStock.java
- src/test/java/com/dokebi/dalkom/domain/option/controller/ProductOptionControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/option/service/ProductOptionServiceTest.java
> [DOK-205] 옵션 테스트코드

- src/test/java/com/dokebi/dalkom/domain/stock/service/ProductStockServiceTest.java
> [DOK-187] 메서드 변경

- src/main/java/com/dokebi/dalkom/domain/cart/controller/OrderCartController.java
- src/main/java/com/dokebi/dalkom/domain/cart/repository/OrderCartRepository.java
- src/main/java/com/dokebi/dalkom/domain/cart/service/OrderCartService.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/controller/InquiryController.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/repository/InquiryRepository.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/InquiryService.java
- src/main/java/com/dokebi/dalkom/domain/mileage/controller/MileageController.java
- src/main/java/com/dokebi/dalkom/domain/notice/controller/NoticeController.java
- src/main/java/com/dokebi/dalkom/domain/notice/repository/NoticeRepository.java
- src/main/java/com/dokebi/dalkom/domain/notice/service/NoticeService.java
- src/main/java/com/dokebi/dalkom/domain/order/controller/OrderController.java
- src/main/java/com/dokebi/dalkom/domain/order/repository/OrderRepository.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/main/java/com/dokebi/dalkom/domain/product/controller/ProductController.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/main/java/com/dokebi/dalkom/domain/review/controller/ReviewController.java
- src/main/java/com/dokebi/dalkom/domain/review/repository/ReviewRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/service/ReviewService.java
- src/test/java/com/dokebi/dalkom/domain/cart/controller/OrderCartControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/cart/repository/OrderCartRepositoryTest.java
- src/test/java/com/dokebi/dalkom/domain/cart/service/OrderCartServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/order/controller/OrderControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/review/controller/ReviewControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/review/repository/ReviewRepositoryTest.java
- src/test/java/com/dokebi/dalkom/domain/review/service/ReviewServiceTest.java
> [DOK-207] 목록에 대한 페이지네이션 추가

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/order/controller/OrderController.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/OrderPageDetailDto.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/OrderStateUpdateRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/exception/OrderNotFoundException.java
- src/main/java/com/dokebi/dalkom/domain/order/exception/OrderStockLackException.java
- src/main/java/com/dokebi/dalkom/domain/order/repository/OrderDetailRepository.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
> [DOK-114] 주문 상태 수정

- src/main/java/com/dokebi/dalkom/domain/category/service/CategoryService.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/controller/InquiryController.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryAnswerRequest.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryListResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryOneResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/repository/InquiryRepository.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/InquiryService.java
- src/test/java/com/dokebi/dalkom/domain/cart/controller/OrderCartControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/controller/InquiryControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryAnswerRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryCreateRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/factory/InquiryAnswerRequestFactory.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/factory/InquiryCreateRequestFactory.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/factory/InquiryListResponseFactory.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/service/InquiryServiceTest.java
문의 테스트 코드 작성 및 오류 수정
문의 테스트 코드 작성 및 오류 수정
> [DOK-211] 문의 테스트 코드 작성 및 오류 수정

- build.gradle
- src/test/java/com/dokebi/dalkom/domain/review/controller/ReviewControllerTest.java
> [DOK-207] 리뷰 컨트롤러 테스팅 오류 수정

- src/main/java/com/dokebi/dalkom/domain/admin/controller/AdminController.java
- src/main/java/com/dokebi/dalkom/domain/admin/repository/AdminRepository.java
- src/main/java/com/dokebi/dalkom/domain/admin/service/AdminService.java
- src/test/java/com/dokebi/dalkom/domain/admin/controller/AdminControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/admin/service/AdminServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/review/controller/ReviewControllerTest.java
관리자 테스트 코드 오류 해결
관리자 테스트 코드 오류 해결
> [DOK-206] 관리자 테스트 코드 오류 해결

- src/main/java/com/dokebi/dalkom/domain/admin/repository/AdminRepository.java
- src/main/java/com/dokebi/dalkom/domain/admin/service/AdminService.java
- src/main/java/com/dokebi/dalkom/domain/cart/controller/OrderCartController.java
- src/main/java/com/dokebi/dalkom/domain/cart/dto/OrderCartCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/cart/dto/OrderCartDeleteRequest.java
- src/main/java/com/dokebi/dalkom/domain/cart/exception/OrderCartEmptyResultDataAccessException.java
- src/main/java/com/dokebi/dalkom/domain/cart/repository/OrderCartRepository.java
- src/main/java/com/dokebi/dalkom/domain/cart/service/OrderCartService.java
- src/test/java/com/dokebi/dalkom/domain/cart/controller/OrderCartControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/cart/repository/OrderCartRepositoryTest.java
orderCartTest 코드 LoginUser 설정, orderCart 코드 리팩토링
orderCartTest 코드 LoginUser 설정, orderCart 코드 리팩토링
> [DOK-191] refactor : orderCartTest 코드 LoginUser 설정, orderCart 코드 리팩토링

- src/main/java/com/dokebi/dalkom/domain/product/controller/ProductController.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ReadProductDetailDTO.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ReadProductDetailResponse.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/StockListDTO.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
product 코드 리펙토링
product 코드 리펙토링
> [DOK-190] product 코드 리펙토링

- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductByCategoryDetailResponse.java
- src/test/java/com/dokebi/dalkom/domain/product/factory/ProductByCategoryDetailResponseFactory.java
- src/test/java/com/dokebi/dalkom/domain/product/factory/ProductByCategoryResponseFactory.java
- src/test/java/com/dokebi/dalkom/domain/product/service/ProductServiceTest.java
> [DOK-216] 상품 테스트 수정

- src/main/java/com/dokebi/dalkom/domain/category/repository/CategoryRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/controller/ProductController.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductByCategoryDetailResponse.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductMainResponse.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/test/java/com/dokebi/dalkom/domain/product/factory/ProductByCategoryDetailResponseFactory.java
> [DOK-226] 오류 임시 조치

- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductByCategoryDetailResponse.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/test/java/com/dokebi/dalkom/domain/order/service/OrderServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/product/controller/ProductControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/product/factory/ProductByCategoryDetailResponseFactory.java
- src/test/java/com/dokebi/dalkom/domain/product/service/ProductServiceTest.java
ProductService 내 readByProductSeq -> readProductByProductSeq로 통일
테스트 메서드 설명용 주석 @DisplayName으로 변경
ProductRepository 내 findProductListByCategory 메서드의 쿼리, 변경된 Dto에 맞춰서 수정
ProductService 및 그 테스트 코드에서 중복, 누락된 메서드 수정
> [DOK-216] 중복, 누락된 메서드 수정

- src/main/java/com/dokebi/dalkom/domain/user/dto/LogInAdminRequest.java
> [DOK-232] 관리자 로그인 시 id 변수명 변경

- src/main/java/com/dokebi/dalkom/domain/category/repository/CategoryRepository.java
- src/main/java/com/dokebi/dalkom/domain/category/service/CategoryService.java
- src/main/java/com/dokebi/dalkom/domain/option/repository/ProductOptionRepository.java
- src/main/java/com/dokebi/dalkom/domain/option/service/ProductOptionService.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/main/java/com/dokebi/dalkom/domain/stock/service/ProductStockService.java
- src/test/java/com/dokebi/dalkom/domain/category/service/CategoryServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/product/service/ProductServiceTest.java
> [DOK-241] 메소드명 리팩토링

- src/main/java/com/dokebi/dalkom/domain/user/dto/LogInUserResponse.java
- src/main/java/com/dokebi/dalkom/domain/user/service/SignService.java
> [DOK-158] 사용자 로그인 시 마일리지 반환

- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryListResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/repository/InquiryRepository.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/InquiryService.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/factory/InquiryListResponseFactory.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/service/InquiryServiceTest.java
> [DOK-249] 문의 API 최적화

- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryOneResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/repository/InquiryRepository.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/InquiryService.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/service/InquiryServiceTest.java
> [DOK-249] 문의 상세를 가져올 때, 응답 상태가 N이면 응답 관련 정보는 가져오지 않도록 수정

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/OrderState.java
- src/main/java/com/dokebi/dalkom/common/response/Response.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageService.java
- src/main/java/com/dokebi/dalkom/domain/order/controller/OrderController.java
- src/main/java/com/dokebi/dalkom/domain/order/exception/InvalidOrderStateException.java
- src/main/java/com/dokebi/dalkom/domain/order/repository/OrderDetailRepository.java
- src/main/java/com/dokebi/dalkom/domain/order/repository/OrderRepository.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderDetailService.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/main/java/com/dokebi/dalkom/domain/review/repository/ReviewRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/service/ReviewService.java
- src/test/java/com/dokebi/dalkom/domain/order/controller/OrderControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/order/service/OrderServiceTest.java
> [DOK-255] 주문 취소 요청 / 환불 확정

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/OrderState.java
- src/main/java/com/dokebi/dalkom/domain/order/controller/OrderController.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/AuthorizeOrderRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/exception/PasswordNotValidException.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
결제 과정중 마일리지 차감을 비밀번호 인증 후로 변경
주문 상태에 인증 전을 나타내는 코드 (10) 추가
> [DOK-257] 비밀번호 인증과정 추가

- src/main/java/com/dokebi/dalkom/domain/inquiry/controller/FaqController.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/FaqCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/FaqReadListResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/FaqReadOneResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/entity/Inquiry.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/repository/FaqRepository.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/FaqService.java
> [DOK-253] FAQ 기능 구현

- src/main/java/com/dokebi/dalkom/domain/order/dto/OrderCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/OrderProductRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/ReceiverInfoRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderDetailService.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/test/java/com/dokebi/dalkom/domain/order/controller/OrderControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/order/dto/OrderCreateRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/order/factory/OrderCreateRequestFactory.java
- src/test/java/com/dokebi/dalkom/domain/order/factory/OrderProductRequestFactory.java
- src/test/java/com/dokebi/dalkom/domain/order/factory/ReceiverInfoRequestFactory.java
- src/test/java/com/dokebi/dalkom/domain/order/service/OrderServiceTest.java
> [DOK-70] 주문 DTO 수정

- src/main/java/com/dokebi/dalkom/common/magicnumber/OrderState.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/AuthorizeOrderRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
> [DOK-257] 결제 전에 인증 과정 오도록 수정

- src/main/java/com/dokebi/dalkom/domain/cart/dto/OrderCartReadResponse.java
- src/main/java/com/dokebi/dalkom/domain/cart/repository/OrderCartRepository.java
- src/main/java/com/dokebi/dalkom/domain/cart/service/OrderCartService.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/FaqReadListResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/repository/FaqRepository.java
- src/main/java/com/dokebi/dalkom/domain/order/controller/OrderController.java
> [DOK-229] FAQ DTO 수정

- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductUpdateRequest.java
> [DOK-107] DTO에 NoArgsConstructor 추가

- src/main/java/com/dokebi/dalkom/common/magicnumber/MileageApplyState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/OrderState.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageApplyService.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductUpdateRequest.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/main/java/com/dokebi/dalkom/domain/user/dto/SignUpRequest.java
- src/main/java/com/dokebi/dalkom/domain/user/entity/Employee.java
- src/main/java/com/dokebi/dalkom/domain/user/entity/User.java
- src/main/java/com/dokebi/dalkom/domain/user/repository/EmployeeRepository.java
- src/main/java/com/dokebi/dalkom/domain/user/service/SignService.java
- src/test/java/com/dokebi/dalkom/domain/cart/service/OrderCartServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/service/InquiryServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/review/service/ReviewServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/user/factory/UserFactory.java
> [DOK-282] 회원가입시 마일리지 자동 지급 로직

- src/main/java/com/dokebi/dalkom/domain/order/controller/OrderController.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/AuthorizeOrderRequest.java
> [DOK-257] 인증이 제대로 작동 안하는 버그 수정

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/controller/FaqController.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/controller/InquiryController.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/FaqUpdateRequest.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/exception/FAQNotFoundException.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/exception/FaqNotFoundException.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/FaqService.java
> [DOK-291] FAQ 수정 

- README.md
> [DOK-293] Readme 임시 작성

- src/main/java/com/dokebi/dalkom/domain/mileage/controller/MileageApplyController.java
- src/main/java/com/dokebi/dalkom/domain/mileage/dto/MileageStateRequest.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageApplyService.java
- src/test/java/com/dokebi/dalkom/domain/mileage/controller/MileageApplyControllerTest.java
> [DOK-293] 마일리지 승인 상태 변경 시 상태값 가져가도록 수정

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/chat/config/ChatGptConfig.java
- src/main/java/com/dokebi/dalkom/domain/chat/controller/ChatGptController.java
- src/main/java/com/dokebi/dalkom/domain/chat/dto/ChatGptMessage.java
- src/main/java/com/dokebi/dalkom/domain/chat/dto/ChatGptRequest.java
- src/main/java/com/dokebi/dalkom/domain/chat/dto/ChatGptResponse.java
- src/main/java/com/dokebi/dalkom/domain/chat/exception/GptNoResponseException.java
- src/main/java/com/dokebi/dalkom/domain/product/controller/ProductController.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductCompareDetailDto.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductCompareDetailResponse.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/main/java/com/dokebi/dalkom/domain/review/dto/ReviewSimpleDto.java
- src/main/java/com/dokebi/dalkom/domain/review/repository/ReviewRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/service/ReviewService.java
> [DOK-294] 상품 비교 API / ChatGPT 연동

- src/main/java/com/dokebi/dalkom/domain/admin/controller/AdminController.java
- src/main/java/com/dokebi/dalkom/domain/admin/service/AdminService.java
- src/main/java/com/dokebi/dalkom/domain/mileage/repository/MileageApplyRepository.java
- src/main/java/com/dokebi/dalkom/domain/option/repository/ProductOptionRepository.java
- src/main/java/com/dokebi/dalkom/domain/option/service/ProductOptionService.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/OrderCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/OrderPageDetailDto.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/OrderProductRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/ReceiverInfoRequest.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/main/java/com/dokebi/dalkom/domain/user/controller/SignController.java
- src/main/java/com/dokebi/dalkom/domain/user/service/SignService.java
- src/test/java/com/dokebi/dalkom/domain/order/dto/OrderPageDetailDtoTest.java
- src/test/java/com/dokebi/dalkom/domain/order/dto/OrderPageDtoTest.java
- src/test/java/com/dokebi/dalkom/domain/order/factory/OrderCreateRequestFactory.java
- src/test/java/com/dokebi/dalkom/domain/order/factory/OrderPageDetailDtoFactory.java
- src/test/java/com/dokebi/dalkom/domain/order/factory/OrderProductRequestFactory.java
> [DOK-70]  관리자 유저 추가 기능 

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/admin/service/AdminService.java
- src/main/java/com/dokebi/dalkom/domain/chat/config/ChatGptConfig.java
- src/main/java/com/dokebi/dalkom/domain/chat/exception/GptNoResponseException.java
- src/main/java/com/dokebi/dalkom/domain/chat/exception/GptResponseFailException.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/FaqService.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageService.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
> [DOK-249] 문제 제거

- src/main/java/com/dokebi/dalkom/domain/user/config/SecurityBeansConfig.java
- src/main/java/com/dokebi/dalkom/domain/user/config/SecurityConfig.java
- src/main/java/com/dokebi/dalkom/domain/user/dto/UserUpdateRequest.java
- src/main/java/com/dokebi/dalkom/domain/user/service/TokenService.java
- src/main/java/com/dokebi/dalkom/domain/user/service/UserService.java
> [DOK-100] 사용자 정보 수정 시 비밀번호 암호화되도록 수정

- src/main/java/com/dokebi/dalkom/domain/order/controller/OrderController.java
> [DOK-249] fix : 잘못 수정했던 API 복구

- .github/checkstyle.xml
- .github/workflows/checkstyle.yml
> [workflow] checkstyle 적용

- src/main/java/com/dokebi/dalkom/domain/admin/controller/AdminController.java
- src/main/java/com/dokebi/dalkom/domain/admin/service/AdminService.java
- src/main/java/com/dokebi/dalkom/domain/user/service/UserService.java
> [DOK-100] 유저 비활성화 기능 

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/AdminRole.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/InquiryAnswerState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/MileageApplyState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/MileageHistoryState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/OrderState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/ProductActiveState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/UserState.java
- src/main/java/com/dokebi/dalkom/domain/admin/entity/Admin.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/FaqService.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/InquiryService.java
- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageApplyService.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/main/java/com/dokebi/dalkom/domain/user/controller/SignController.java
- src/main/java/com/dokebi/dalkom/domain/user/entity/User.java
- src/main/java/com/dokebi/dalkom/domain/user/repository/UserRepository.java
- src/main/java/com/dokebi/dalkom/domain/user/service/SignService.java
> [DOK-158] 로그아웃 기능 추가 / state 값 enum으로 변경

- src/main/java/com/dokebi/dalkom/common/magicnumber/MileageApplyState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/OrderState.java
- src/main/java/com/dokebi/dalkom/domain/mileage/dto/MileageApplyResponse.java
- src/main/java/com/dokebi/dalkom/domain/order/dto/OrderAdminReadResponse.java
> [DOK-304] state response에 한글명도 반환하도록 수정

- src/main/java/com/dokebi/dalkom/common/magicnumber/AdminRole.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/InquiryAnswerState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/MileageApplyState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/MileageHistoryState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/OrderState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/ProductActiveState.java
- src/main/java/com/dokebi/dalkom/common/magicnumber/UserState.java
> [DOK-304] enum 메소드 추가

- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductByCategoryDetailPage.java
- src/main/java/com/dokebi/dalkom/domain/product/dto/ProductByCategoryDetailResponse.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/test/java/com/dokebi/dalkom/domain/product/factory/ProductByCategoryDetailResponseFactory.java
- src/test/java/com/dokebi/dalkom/domain/product/service/ProductServiceTest.java
> [DOK-241] 하위카테고리별 상품 리스트 반환시 카테고리 이름도 같이 반환

- src/main/java/com/dokebi/dalkom/domain/order/repository/OrderDetailRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/controller/ReviewController.java
- src/main/java/com/dokebi/dalkom/domain/review/dto/ReviewReadResponse.java
- src/main/java/com/dokebi/dalkom/domain/review/repository/ReviewRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/service/ReviewService.java
> [DOK-308] feat : 단일 리뷰 정보 조회 (리뷰 수정시 표시)

- src/main/java/com/dokebi/dalkom/domain/order/repository/OrderRepository.java
> [DOK-70] fix : 에러 수정

- src/main/java/com/dokebi/dalkom/domain/option/dto/OptionDetailListResponse.java
- src/main/java/com/dokebi/dalkom/domain/option/repository/ProductOptionRepository.java
- src/main/java/com/dokebi/dalkom/domain/option/service/ProductOptionService.java
- src/test/java/com/dokebi/dalkom/domain/option/service/ProductOptionServiceTest.java
> [DOK-190] API 수정 요청 완료

- src/main/java/com/dokebi/dalkom/domain/notice/controller/NoticeController.java
- src/main/java/com/dokebi/dalkom/domain/notice/dto/NoticeUpdateRequest.java
- src/main/java/com/dokebi/dalkom/domain/notice/service/NoticeService.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderService.java
- src/test/java/com/dokebi/dalkom/domain/notice/controller/NoticeControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/notice/dto/NoticeUpdateRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/notice/factory/NoticeUpdateRequestFactory.java
- src/test/java/com/dokebi/dalkom/domain/notice/service/NoticeServiceTest.java
> [DOK-293] 공지 수정 api 수정

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/review/exception/ReviewAlreadyExistsException.java
- src/main/java/com/dokebi/dalkom/domain/review/repository/ReviewRepository.java
- src/main/java/com/dokebi/dalkom/domain/review/service/ReviewService.java
pull request review 횟수를 줄이기 위해 DOK-96으로 merge
> [DOK-89] 한명이 하나의 주문상세에 두개의 리뷰를 작성할 수 없도록 수정

- src/main/java/com/dokebi/dalkom/common/advice/ExceptionAdvice.java
- src/main/java/com/dokebi/dalkom/domain/admin/repository/AdminRepository.java
- src/main/java/com/dokebi/dalkom/domain/chat/dto/ChatGptResponse.java
- src/main/java/com/dokebi/dalkom/domain/notice/repository/NoticeRepository.java
> [DOK-89] 공지사항 날짜 내림차순

- src/main/java/com/dokebi/dalkom/domain/admin/controller/AdminController.java
- src/main/java/com/dokebi/dalkom/domain/admin/dto/AdminDashboardResponse.java
- src/main/java/com/dokebi/dalkom/domain/admin/dto/MonthlyCategoryListDto.java
- src/main/java/com/dokebi/dalkom/domain/admin/dto/MonthlyPriceListDto.java
- src/main/java/com/dokebi/dalkom/domain/admin/dto/MonthlyProductListDto.java
- src/main/java/com/dokebi/dalkom/domain/admin/repository/AdminRepository.java
- src/main/java/com/dokebi/dalkom/domain/admin/service/AdminService.java
> [DOK-286] 관리자 대시보드 기능 추가

- src/main/java/com/dokebi/dalkom/domain/product/entity/Product.java
- src/test/java/com/dokebi/dalkom/domain/stock/controller/ProductStockControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/stock/service/ProductStockServiceTest.java
pull request 리뷰 횟수 줄이기 위해 70으로 merge
> [DOK-187] test : 테스트 개선

- src/test/java/com/dokebi/dalkom/domain/option/controller/ProductOptionControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/option/service/ProductOptionServiceTest.java
pull request review 최소화를 위해 DOK-70에 merge
> [DOK-205] 테스트 코드 최신화

- src/test/java/com/dokebi/dalkom/domain/product/factory/OptionAmountDtoListFactory.java
- src/test/java/com/dokebi/dalkom/domain/product/service/ProductServiceTest.java
pull request review 수 최소화를 위해 DOK-70에 merge
> [DOK-216] 상품 테스트 코드 최신화

- src/main/java/com/dokebi/dalkom/domain/user/dto/UserUpdateRequest.java
- src/main/java/com/dokebi/dalkom/domain/user/service/UserService.java
> [DOK-158] 개인정보 수정 > 비밀번호 암호화 / 닉네임 중복성 수정

- src/main/java/com/dokebi/dalkom/domain/cart/dto/OrderCartReadResponse.java
- src/main/java/com/dokebi/dalkom/domain/cart/service/OrderCartService.java
- src/test/java/com/dokebi/dalkom/domain/cart/controller/OrderCartControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/cart/dto/OrderCartReadResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/cart/service/OrderCartServiceTest.java
OrderCart 테스트 코드 작성 완료
OrderCart 테스트 코드 작성 완료
> [DOK-191] OrderCart 테스트 코드 작성 완료

- src/main/java/com/dokebi/dalkom/domain/inquiry/controller/InquiryController.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryAnswerRequest.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryCreateRequest.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryListByUserResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryListResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryOneResponse.java
- src/main/java/com/dokebi/dalkom/domain/inquiry/service/InquiryService.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/controller/InquiryControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryAnswerRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryCreateRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryListByUserResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryListResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryOneResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/service/InquiryServiceTest.java
INQUIRY 테스트 코드 작성 완료
INQUIRY 테스트 코드 작성 완료
> [DOK-211] INQUIRY 테스트 코드 작성 완료

- src/main/java/com/dokebi/dalkom/domain/mileage/repository/MileageHistoryRepository.java
플리퀘 리뷰 수를 줄이기 위해 DOK-294로 merge
> [DOK-102] feat: 마일리지 히스토리 최신순 정렬

- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/test/java/com/dokebi/dalkom/domain/category/factory/CategoryFactory.java
- src/test/java/com/dokebi/dalkom/domain/category/factory/SubCategoryResponseFactory.java
- src/test/java/com/dokebi/dalkom/domain/product/service/ProductServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/stock/factory/StockFactory.java
> [DOK-216] 상품 테스트에서 빼먹은 메서드에 대한 테스트코드 추가

- src/main/java/com/dokebi/dalkom/domain/Analyze.java
- src/main/java/com/dokebi/dalkom/domain/admin/dto/MonthlyPriceListDto.java
- src/main/java/com/dokebi/dalkom/domain/admin/dto/MonthlyProductListDto.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderDetailService.java
- src/test/java/com/dokebi/dalkom/domain/admin/dto/AdminDashboardResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/admin/dto/MonthlyCategoryListDtoTest.java
- src/test/java/com/dokebi/dalkom/domain/admin/repository/AdminRepositoryTest.java
- src/test/java/com/dokebi/dalkom/domain/admin/service/AdminServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/cart/dto/OrderCartReadResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/controller/FaqControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/FaqCreateRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/FaqReadListResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/FaqReadOneResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/FaqUpdateRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryListByUserResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryListResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/dto/InquiryOneResponseTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/repository/FaqRepositoryTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/repository/InquiryRepositoryTest.java
- src/test/java/com/dokebi/dalkom/domain/inquiry/service/FaqServiceTest.java
- src/test/java/com/dokebi/dalkom/domain/mileage/dto/MileageStateRequestTest.java
- src/test/java/com/dokebi/dalkom/domain/user/controller/SignControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/user/controller/UserControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/user/service/UserServiceTest.java
> [DOK-241] 리팩토링

- src/main/java/com/dokebi/dalkom/domain/chat/dto/ChatGptResponse.java
- src/main/java/com/dokebi/dalkom/domain/jira/service/JiraService.java
- src/main/java/com/dokebi/dalkom/domain/option/entity/ProductOption.java
- src/main/java/com/dokebi/dalkom/domain/order/service/OrderDetailService.java
- src/main/java/com/dokebi/dalkom/domain/user/config/SecurityBeansConfig.java
- src/main/java/com/dokebi/dalkom/domain/user/config/SecurityConfig.java
- src/main/java/com/dokebi/dalkom/domain/user/service/SignService.java
> [DOK-241] refactor : 리팩토링

- src/test/java/com/dokebi/dalkom/domain/product/service/ProductServiceTest.java
> [DOK-216] 분기 커버리지 약간 추가

- src/main/java/com/dokebi/dalkom/domain/mileage/service/MileageService.java
- src/main/resources/application.yml
> [DOK-293] 로그인 시 마일리지 가져오도록 수정

- src/main/resources/com/dokebi/dalkom/domain/admin/mapper/AdminMapper.xml
> [DOK-354] 데이터가 있어도 null이 전송되던 에러 수정

- src/main/java/com/dokebi/dalkom/domain/user/controller/UserController.java
- src/main/java/com/dokebi/dalkom/domain/user/dto/UserUpdateRequest.java
- src/main/java/com/dokebi/dalkom/domain/user/service/RedisService.java
- src/main/java/com/dokebi/dalkom/domain/user/service/SignService.java
- src/main/java/com/dokebi/dalkom/domain/user/service/TokenService.java
- src/main/java/com/dokebi/dalkom/domain/user/service/UserService.java
- src/test/java/com/dokebi/dalkom/domain/user/controller/UserControllerTest.java
- src/test/java/com/dokebi/dalkom/domain/user/service/UserServiceTest.java
사용자 본인 정보 REDIS 적용 완료
사용자 본인 정보 REDIS 적용 완료
> [DOK-158] 사용자 본인 정보 REDIS 적용 완료

- build.gradle
- src/main/java/com/dokebi/dalkom/common/config/ElasticsearchConfig.java
- src/main/java/com/dokebi/dalkom/domain/product/entity/ProductElasticsearch.java
- src/main/java/com/dokebi/dalkom/domain/product/repository/ProductRepository.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductElasticService.java
- src/main/java/com/dokebi/dalkom/domain/product/service/ProductService.java
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
> [DOK-334] 사용자 메인화면 상품 검색 시 유의어 기반 검색 추가 (엘라스틱 연동)
